"""Base async Ollama agent bridge for xv7 orchestration."""

from __future__ import annotations

import asyncio
import os
import re
from pathlib import Path
from typing import Any

import httpx

try:
    import yaml
except ImportError:  # pragma: no cover - handled at runtime if unavailable
    yaml = None

from core.runtime.schemas import ConversationMessage, SessionState


class BaseAgent:
    """Async agent wrapper around Ollama's `/api/chat` endpoint.

    The agent reuses a single `httpx.AsyncClient` instance for connection pooling
    and non-blocking request throughput.
    """

    def __init__(self) -> None:
        base_url = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434").rstrip("/")
        timeout = httpx.Timeout(connect=10.0, read=600.0, write=30.0, pool=10.0)
        limits = httpx.Limits(max_connections=100, max_keepalive_connections=20)

        self.personas = self._load_personas()
        self._client = httpx.AsyncClient(
            base_url=base_url,
            timeout=timeout,
            limits=limits,
        )

    async def aclose(self) -> None:
        """Close the underlying HTTP client and free pooled connections."""
        await self._client.aclose()

    async def generate_response(self, session_state: SessionState) -> str:
        """Generate a model response from the full active session history.

        Args:
            session_state: Current user session with ordered conversation history.

        Returns:
            Raw assistant text generated by Ollama.

        Raises:
            RuntimeError: If Ollama request/response handling fails.
            ValueError: If no usable response content is returned.
        """
        persona = self.personas.get(session_state.current_persona)
        model = self._resolve_model(session_state.current_persona, persona)

        options: dict[str, Any] = {
            "num_ctx": 8192,
            "num_predict": 1024,
        }
        persona_options = persona.get("options") if isinstance(persona, dict) else None
        if isinstance(persona_options, dict):
            options.update(persona_options)

        messages = [self._to_ollama_message(message) for message in session_state.messages]
        persona_system_prompt = persona.get("system_prompt") if isinstance(persona, dict) else None
        if isinstance(persona_system_prompt, str) and persona_system_prompt.strip():
            messages.insert(
                0,
                {
                    "role": "system",
                    "content": persona_system_prompt.strip(),
                },
            )

        payload = {
            "model": model,
            "stream": False,
            "keep_alive": -1,
            "options": options,
            "messages": messages,
        }

        response: httpx.Response | None = None
        max_attempts = 2
        for attempt in range(1, max_attempts + 1):
            try:
                response = await self._client.post("/api/chat", json=payload)
                response.raise_for_status()
                break
            except httpx.TimeoutException as exc:
                raise RuntimeError("Timed out while calling Ollama /api/chat") from exc
            except httpx.HTTPStatusError as exc:
                detail = exc.response.text
                is_startup_timeout = (
                    exc.response.status_code == 500
                    and "timed out waiting for llama-server to start" in detail
                )
                if is_startup_timeout and attempt < max_attempts:
                    await asyncio.sleep(2.0)
                    continue
                raise RuntimeError(
                    f"Ollama /api/chat failed with status {exc.response.status_code}: {detail}"
                ) from exc
            except httpx.HTTPError as exc:
                raise RuntimeError(f"Failed to call Ollama /api/chat: {exc}") from exc

        if response is None:
            raise RuntimeError("Ollama /api/chat did not return a response")

        data: dict[str, Any] = response.json()
        message = data.get("message")
        if not isinstance(message, dict):
            raise ValueError("Invalid Ollama response: missing 'message' object")

        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            raise ValueError("Invalid Ollama response: missing assistant content")

        return content

    @staticmethod
    def _resolve_model(current_persona: str, persona: dict[str, Any] | None = None) -> str:
        """Resolve model from persona config, then env vars, then fallback."""
        if isinstance(persona, dict):
            persona_model = persona.get("model")
            if isinstance(persona_model, str) and persona_model.strip():
                return persona_model.strip()

        persona_key = re.sub(r"[^A-Za-z0-9]+", "_", current_persona).strip("_").upper()
        if persona_key:
            persona_model = os.getenv(f"MODEL_{persona_key}")
            if persona_model:
                return persona_model

        return os.getenv("MODEL_DEFAULT", "llama3")

    @staticmethod
    def _to_ollama_message(message: ConversationMessage) -> dict[str, str]:
        """Convert internal message to Ollama chat message schema.

        If reasoning content exists, it is re-injected as a `<|think|>` block so
        downstream turns can preserve reasoning continuity.
        """
        if message.reasoning_content:
            content = (
                f"<|think|>{message.reasoning_content}</|think|>\n"
                f"{message.content}"
            )
        else:
            content = message.content

        return {
            "role": message.role,
            "content": content,
        }

    @staticmethod
    def _load_personas() -> dict[str, dict[str, Any]]:
        """Load persona registry from YAML config with graceful fallbacks."""
        if yaml is None:
            return {}

        candidates: list[Path] = []
        config_override = os.getenv("PERSONAS_CONFIG_PATH")
        if config_override:
            candidates.append(Path(config_override))

        candidates.append(Path(__file__).resolve().parents[2] / "config" / "personas.yaml")
        candidates.append(Path.cwd() / "config" / "personas.yaml")

        config_path = next((path for path in candidates if path.exists()), None)
        if config_path is None:
            return {}

        try:
            parsed = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        except Exception:
            return {}

        if not isinstance(parsed, dict):
            return {}

        raw_personas = parsed.get("personas", parsed)
        if not isinstance(raw_personas, dict):
            return {}

        personas: dict[str, dict[str, Any]] = {}
        for key, value in raw_personas.items():
            if not isinstance(key, str) or not isinstance(value, dict):
                continue
            personas[key] = value

        return personas
